version: '3.8'
services:
  mystore-basic:
    build: ./mystore-basic
    image: mystore-basic
    container_name: mystore-basic
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - mystore-payment
      - redis-db
      - keycloak-srv
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - PAYMENT_SERVICE_URL=mystore-payment
      - PAYMENT_SERVICE_PORT=8091
      - KEYCLOAK_HOST=keycloak-srv
      - KEYCLOAK_PORT=8080

  mystore-payment:
    build: ./mystore-payment
    image: mystore-payment
    container_name: mystore-payment
    ports:
      - "8091:8091"
    depends_on:
      - keycloak-srv
    environment:
      - KEYCLOAK_HOST=keycloak-srv
      - KEYCLOAK_PORT=8080

  redis-db:
    image: redis:7.4.2-bookworm
    container_name: redis-db
    ports:
      - "6379:6379"

  keycloak-srv:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak-srv
    ports:
      - 8081:8080
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: "-v start-dev --import-realm"