server:
  port: 8091

spring:
  application:
    name: payment
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/my-store"