server:
  port: 8090

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:stats;MODE=PostgreSQL
    username: test
    password: test