server:
  port: 8090

spring:
  r2dbc:
    url: r2dbc:h2:mem:///~/db/testdb
    username: test
    password: test
  liquibase:
    url: jdbc:h2:mem:~/db/testdb;DB_CLOSE_DELAY=-1
    user: test
    password: test
    enabled: true

