spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cache:
    redis:
      time-to-live: PT5S    # TTL по умолчанию для кешей

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/master # Адрес сервера авторизации для получения токена
        registration:
          mystore:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: mystore
            client-secret: cznQEDKlvjyPzSBYPzKuEMPgUnZdzOFy
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета
            scope: profile

app-pref:
  payment-service:
    url: "http://127.0.0.1:8091"