server:
  port: 8090

spring:
  r2dbc:
    url: r2dbc:h2:mem:///~/db/testdb
    username: test
    password: test
  liquibase:
    url: jdbc:h2:mem:~/db/testdb;DB_CLOSE_DELAY=-1
    user: test
    password: test
    enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: "http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/my-store" # Адрес сервера авторизации для получения токена
        registration:
          mystore:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: mystore
            client-secret: PGFL4KWeBT8SpnTTqs2CuUrw7bnvPlqE
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета
            scope: profile

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    cache:
      redis:
        time-to-live: PT5S    # TTL по умолчанию для кешей

app-pref:
  payment-service:
    url: "http://${PAYMENT_SERVICE_URL}:${PAYMENT_SERVICE_PORT}"